### ISSUE TITLE
external SQL

### ISSUE THREAD

**Issue by elstringer** [doomsider/shadow#2]
hello is it possible you to use an external database for the script in the configuration ?

**Comment by doomsider** [comment]
The script uses Mysql right now.

**Comment by elstringer** [comment]
Yes, but it is mandatory that mysql am insalled on the same machine as the server! my database is currently on a server other than the game server !

[starmade@starmade:~/alpha] ./shadow.dtsd setup
No configuration file detected [/home/starmade/alpha/config.dtsd] please run shadow.dtsd setup
Press enter to accept default answer in brackets or type in your setting. Note: running this will overwrite existing configuration
Do you wish to setup DTSD? [No] / Yes : y
Setting up config file
Doing basic test for Java installation.  Note:  This does not check for version compatibility
Java found
Doing basic test for Mysql installation.
Doing basic test for Screen installation.
Screen found
Please install mysql.  IE: for Ubuntu type - sudo apt-get install mysql-server libapache2-mod-auth-mysql php5-mysql
[starmade@starmade:~/alpha]

added in the configuration file for the added field the database without mysql installed

my OS Archlinux

**Comment by doomsider** [comment]
Oh well that is like a lot more complex running Mysql remotely.  I will
probably tackle this at some point, but getting the script running
correctly will take priority.

Thinking about it now.... it should be entirely possible by changing the
user to a remote one

On the other hand why not just install Mysql to the game server?

**Comment by doomsider** [comment]
FYI https://wiki.archlinux.org/index.php/MySQL

**Comment by elstringer** [comment]
I use an external MariaDB vm !
Avoided cree for an exorbitant number of database for chauqe vm for each service.
you use mysql or mysqli ?
compared to php and apache are the latest versions you a try?
because with archlinux I use the last existing package !

**Comment by doomsider** [comment]
Well Shadow is being tested right now and the environment to get it to work
in best would be a virtual box (or similar program) Ubuntu with Mysql,
Java, and Screen installed.

Due to being in development right now the use of other operating systems,
remote databases, etc. cannot be supported by me directly.  Once I have
gotten Shadow to a beta stage I will start looking into supporting unique
configurations.

If you want to join the team so to speak I would suggest running a virtual
machine with the latest version of Ubuntu for testing.  I can also add you
as an contributor and that way you can add code or make comments directly
to shadow.

**Comment by elstringer** [comment]
I will created a test environment for tried ! celont is now you're telling me you can not set up multiple servers managed by Shadow on a single machine?
I willing participated in the development of Shadow !
I looked forward to the mysql remote functionality

**Comment by doomsider** [comment]
Shadow will be able to run multiple servers but I have not decided whether each server will have its own server script or if shadow will be ran as a master script for all the servers.
