### ISSUE TITLE
Vote points are added back after stop and restart

### ISSUE THREAD

**Issue by zuch0698o** [doomsider/shadow#5]
Step to replicate

Stop -r server properly

after terminated start -r and allow to boot

votes were readded EX i had 18 points when i had logged out last night, used 9 and, then played for a few hours before restarting after some changes.  I had 18 again when the server was restarted when I should have only had 9 points

Scriptscreen http://pastebin.com/9s4EM7Ve

Mainscreen http://pastebin.com/dQkRY3vi

**Comment by doomsider** [comment]
I have gone over the Vote function but I did not catch where this error is occurring.  It is most likely a logical error in the code.  Another thing that concerned me was on boarding for zuch0698o,  You see the boarding string's name cut as zuch0698o] not  zuch0698o which is ofc a problem for matching.  I can't resolve this additional bug unless I can see the mainlog string that produced this event. 

I may have to just rewrite the vote function piece by piece from scratch to figure this out because I am not having much luck.

**Comment by zuch0698o** [comment]
closing this issue since the vote rework will most likely fix
