### ISSUE TITLE
Crash while trying to restart and backup the universe.

### ISSUE THREAD

**Issue by thakyZ** [doomsider/shadow#6]
So I found out why my server has been crashing and here is the log: http://pastebin.com/MNdw7SVT
The server seems to want to restart the server and then trying to back it up but it cannot because of an error.
`ERROR 1537 (HY000) at line 1: Event 'SERVERRESTART' already exists`
`this is SCHEDULETYPE SYSTEM`
`ERROR 1537 (HY000) at line 1: Event 'SERVERUNIVERSEBACKUP' already exists`

**Comment by doomsider** [comment]
Those errors are simply stating that the event SERVERRESTART and SERVERUNIVERSEBACKUP are already in the events tables and do no indicate a problem.  Not sure what is causing the crashing.  How frequent is it?  There is a 5 minutes server check that sends a message to the server and then shuts down the server and restart it if so.  If it is crashing a lot it may be related to the server becoming unresponsive.  Let me know if you have any more information about this.

**Comment by thakyZ** [comment]
Resolved I found out what it was and can you make it so if you are in the screen you can rejoin back in when the screen closes or at least don't kill the screen...?

**Comment by doomsider** [comment]
That is an interesting suggestion the issue is that I terminate the screens to ensure everything gets a term signal to shutdown.  This is just another way to ensure there are no running processes from previous instances of the server or the script.  Changing this behavior would have to rely on gathering PID and storing them and ensuring everything is stopped.  I will contemplate this.
